### ISSUE TITLE
作者还在吗？没看到源码啊

### ISSUE THREAD

**Issue by 872119925** [wuGuangLei/ityxb-tools#1]
我是个软工大二学生，天天要网课，作业还多，就传智的高校学习平台没自动脚本。，佛了

**Comment by NoahCodeGG** [comment]
> 我是个软工大二学生，天天要网课，作业还多，就传智的高校学习平台没自动脚本。，佛了

因为脚本写的很烂只是为了实现功能所以就没上传脚本，现已上传，感谢使用
